name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pytest
        run: pip install pytest

      - name: Jalankan test
        run: pytest